// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDYxicYXZJF2xSBmQcVY90Pkhk0_y9k70',
    appId: '1:410201815396:web:6f256e7abab010f0f7e271',
    messagingSenderId: '410201815396',
    projectId: 'edubotics-attendance',
    authDomain: 'edubotics-attendance.firebaseapp.com',
    storageBucket: 'edubotics-attendance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyC2vpbbv_OH6pd8O1aub5DKamypJXeLPMY',
  appId: '1:410201815396:android:2c7271dcac9cd013f7e271',
  messagingSenderId: '410201815396',
  projectId: 'edubotics-attendance',
  storageBucket: 'edubotics-attendance.firebasestorage.app',
  databaseURL:
      'https://edubotics-attendance-default-rtdb.asia-southeast1.firebasedatabase.app',
);

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOOS8jax-05yV9hebLeoXg8-Q2zYHrQtA',
    appId: '1:410201815396:ios:b947a629f9bcc938f7e271',
    messagingSenderId: '410201815396',
    projectId: 'edubotics-attendance',
    storageBucket: 'edubotics-attendance.firebasestorage.app',
    iosBundleId: 'com.example.punchinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOOS8jax-05yV9hebLeoXg8-Q2zYHrQtA',
    appId: '1:410201815396:ios:b947a629f9bcc938f7e271',
    messagingSenderId: '410201815396',
    projectId: 'edubotics-attendance',
    storageBucket: 'edubotics-attendance.firebasestorage.app',
    iosBundleId: 'com.example.punchinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDYxicYXZJF2xSBmQcVY90Pkhk0_y9k70',
    appId: '1:410201815396:web:e7e21ed76f711aa6f7e271',
    messagingSenderId: '410201815396',
    projectId: 'edubotics-attendance',
    authDomain: 'edubotics-attendance.firebaseapp.com',
    storageBucket: 'edubotics-attendance.firebasestorage.app',
  );
}
